<a href="https://colab.research.google.com/github/Leo-Mtz/mineria-de-datos/blob/main/Code1_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de datos

## Parcial 1

### Introduccion

#### Conceptos

La minería de datos, en términos sencillos, es el proceso de descubrir patrones, tendencias y conocimientos útiles a partir de grandes conjuntos de datos. Es como encontrar una aguja en un pajar, pero con información. Se utiliza para predecir comportamientos, identificar riesgos, mejorar decisiones y mucho más.

##### Ciencia de Datos

La ciencia de datos es el campo que usa métodos científicos, algoritmos y sistemas para extraer conocimiento y 'insights' de los datos, combinando estadísticas, programación y conocimiento del negocio.

#### IPython Magic Commands

In [81]:
%timeit L= [n ** 2 for n in range(1000)]

70.4 µs ± 948 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [82]:
%timeit?

In [83]:
def donothing(x):
  return x

In [84]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [85]:
%cd sample_data/

[Errno 2] No such file or directory: 'sample_data/'
/content/sample_data


In [86]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [87]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '1c59587657c0',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

In [88]:
import numpy as np

In [89]:
import array
L= list(range(10))
A= array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [91]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [92]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The Basics of Numpy Arrays

In [93]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [94]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [95]:
print("dtype:", x3.dtype)

dtype: int64


In [96]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [97]:
x1

array([5, 0, 3, 3, 7, 9])

In [98]:
x1[0]

np.int64(5)

In [99]:
x1[4]

np.int64(7)

In [100]:
x1[-2]

np.int64(7)

In [101]:
x1[-1]

np.int64(9)

In [102]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [103]:
x2[0, 0]

np.int64(3)

In [104]:
x2[2,-1]

np.int64(7)

##Analisis Estadistico Basico con Numpy

In [105]:
import numpy as np

In [106]:
#Media

In [107]:

data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


In [108]:
#Promedio

In [109]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)


In [110]:
#Promedio Ponderado

In [111]:
promedio_ponderado = np.average(data, weights=weights)

In [112]:
#Mediana

In [113]:
mediana = np.median(data)

In [114]:
#Varianza

In [115]:
varianza = np.var(data)


In [116]:
#Desviacion estandar

In [117]:
desviacion = np.std(data)

##Correlacion

In [118]:
promedio_ponderado = np.average(data, weights=weights)

##Generacion de datos aleatorios

In [119]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


##Cuadros estadisticos

In [120]:

import numpy as np
import pandas as pd
from io import StringIO

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)



In [121]:
edad[:5]

array([22., 21., 26., 21., 24.])

In [122]:
prog_py[:5]

array([ True,  True,  True,  True,  True])

In [123]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),
    'p25': float(np.percentile(edad, 25)),
    'mediana': float(np.median(edad)),
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)),
    'std_muestral': float(np.std(edad, ddof=1)),
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),
}


In [124]:
summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [125]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}


In [126]:
print(f'Frecuencia de utilizacion de python: {freq_python}')
print(f'Frecuencia de utilizacion de colab: {freq_colab}')
print(f'Frecuencia de utilizacion de github: {freq_gh}')

Frecuencia de utilizacion de python: {'Si': 54, 'No': 6}
Frecuencia de utilizacion de colab: {'Si': 18, 'No': 42}
Frecuencia de utilizacion de github: {'Si': 52, 'No': 8}


In [127]:
# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [129]:
print(f'Tabla 2x2 mostrando frecuencias de uso de python y colab: \n{tab_py_colab}')

Tabla 2x2 mostrando frecuencias de uso de python y colab: 
[[ 6  0]
 [36 18]]


In [ ]:
copiar texto, reemplazar /t por una , y subirlo
