<a href="https://colab.research.google.com/github/Leo-Mtz/mineria-de-datos/blob/main/Code1_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de datos

## Parcial 1

### Introduccion

#### Conceptos

La minería de datos, en términos sencillos, es el proceso de descubrir patrones, tendencias y conocimientos útiles a partir de grandes conjuntos de datos. Es como encontrar una aguja en un pajar, pero con información. Se utiliza para predecir comportamientos, identificar riesgos, mejorar decisiones y mucho más.

##### Ciencia de Datos

La ciencia de datos es el campo que usa métodos científicos, algoritmos y sistemas para extraer conocimiento y 'insights' de los datos, combinando estadísticas, programación y conocimiento del negocio.

#### IPython Magic Commands

In [74]:
%timeit L= [n ** 2 for n in range(1000)]

79.1 µs ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [75]:
%timeit?

In [76]:
def donothing(x):
  return x

In [77]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [78]:
%cd sample_data/

[Errno 2] No such file or directory: 'sample_data/'
/content/sample_data


In [79]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [80]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'a965fbcf68ca',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

In [81]:
import numpy as np

In [82]:
import array
L= list(range(10))
A= array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [84]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [85]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The Basics of Numpy Arrays

In [86]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [87]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [88]:
print("dtype:", x3.dtype)

dtype: int64


In [89]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [90]:
x1

array([5, 0, 3, 3, 7, 9])

In [91]:
x1[0]

np.int64(5)

In [92]:
x1[4]

np.int64(7)

In [93]:
x1[-2]

np.int64(7)

In [94]:
x1[-1]

np.int64(9)

In [95]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [96]:
x2[0, 0]

np.int64(3)

In [97]:
x2[2,-1]

np.int64(7)